### PR TITLE
MAISTRA-1352 remove unused helm templates

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
LGTM

My only comment is that now we have some stuff being done within patch-charts.sh (removal of files) and others in the Makefile. I dream with the day we can see this:
```
diff --git a/build/patch-charts.sh b/build/patch-charts.sh
deleted file mode 100755
index 57b33e65..00000000
--- a/build/patch-charts.sh
+++ /dev/null
```

**Comment by rcernich** [comment]
Yeah, I did that out of expediency, and because I didn't want to have to update maistra-1.0 branch.  Eventually, we should push the relevant changes down into the maistra-1.0 branch.  (#405 is even worse, since the changes only apply to the 1.1.1 operator, even though they're 1.0.x charts.)

**Review by luksa — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
> @rcernich: The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> gen-check 	[cb3218b](https://github.com/Maistra/istio-operator/commit/cb3218b6719a84531383f46dc433ec622ee83419) 	[link](https://prow.maistra.io/view/gcs/maistra-prow-testing/pr-logs/pull/Maistra_istio-operator/410/gen-check/1265291368792592384) 	`/test gen-check`

test failure will resolve itself once https://github.com/Maistra/istio-operator/pull/443 is merged (needs rebase)

**Comment by luksa** [comment]
@rcernich I think this needs to be rebased to pass gen-check.

**Comment by rcernich** [comment]
@Mergify refresh

**Comment by rcernich** [comment]
@Mergifyio refresh

**Pull request merged**
