### PR TITLE
MAISTRA-2014 fix external jaeger integration for 1.1 control planes

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

### CODE REVIEW

**Review by dgn — APPROVED** [review]

**Comment by FilipB** [comment]
Can we merge this so we can test https://github.com/openshift/openshift-docs/pull/27423 ?

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
I think it's failing because the other PR got merged, this one probably needs a rebase with a new make gen.

**Pull request merged**
