### PR TITLE
Added support for generating secrets for the Jaeger<->ES communication

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
cc @knrc, @rcernich, @objectiser

This is a first draft, just to check if the direction is valid. Basically, this PR adds another `preprocessObject` hook for the `Jaeger` kind. When `production-elasticsearch` is used, it checks whether the required secrets exist. When they are absent, new certs are generated locally in the `istio-operator` process and set as fields that are then used by the new secret templates inside the `tracing` chart.

What's missing:
- Changes to the existing templates (jaeger and ES)
- Add the secrets to the list of templates to be processed
- Testing (manual, as it seems there are no tests in this repo?)

What I don't know:
- Whether the values that I set in the `populateCertValues` end up in the secret templates
- If the general approach is valid and would be acceptable

**Comment by objectiser** [comment]
Submitted #126 to show the alternative elasticsearch operator approach.

**Comment by rcernich** [comment]
What is the use case that is driving these changes?  Why would we be doing this versus letting k8s generate the certs for us?

**Comment by jpkrohling** [comment]
> What is the use case that is driving these changes?

We had a few problems with the ES operator during the last week, to the point where we thought we might not be able to use it for GA. Most are sorted out already, but this PR brings a way to create an ES cluster based on templates instead of the operator, should we need to move away from the ES-operator.

> Why would we be doing this versus letting k8s generate the certs for us?

I actually did consider generating the CSR's via Go and sending `CertificateSigningRequest` objects to Kubernetes for signing, but that's not how it's currently done by the [Jaeger Operator](https://github.com/jaegertracing/jaeger-operator/blob/master/scripts/cert_generation.sh) nor [ECL Operator](https://github.com/openshift/cluster-logging-operator/blob/master/scripts/cert_generation.sh). If we do decide to follow this approach, I'd be more than happy to consider moving away from this shell script for the next release.

**Comment by jpkrohling** [comment]
I'm closing this, in favor of using the ES Operator. \o/

**Pull request closed without merging**
