### PR TITLE
OSSM-1951 Fix use of deprecated policy/v1beta1 PodDisruptionBudget [maistra-2.0]

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
@jwendell any idea why we changed the yq implementation in 2.0 builds?

**Comment by jwendell** [comment]
@luksa perhaps you need to backport this to 2.0? https://github.com/maistra/istio-operator/pull/682

**Comment by luksa** [comment]
It turns out it was because the version of the yq-python tool is no longer 2.x, but 3.x. I've changed how the generate-manifests script checks the version (see #982).

**Comment by luksa** [comment]
gen-check will pass when #982 is merged

**Review by jewertow — APPROVED** [review]

**Pull request merged**
