### PR TITLE
MAISTRA-1431 ControlPlaneStatus.ComponentStatus array shouldn't be an array of pointers

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
This PR also contains #422, which must be merged first.

**Review by rcernich — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
Isn't it better to have them as pointers to avoid copies?

**Comment by luksa** [comment]
> Isn't it better to have them as pointers to avoid copies?

Semantically they shouldn't be pointers. Also, the `FindComponentByName()` function will still return a pointer to the array element, since the existing code expects that modifications of the object will be applied to the array element. We never really copy the object except when making a copy of the whole SMCP. But then we always make a deep copy, so even if we used a pointer, the object would be copied.

**Comment by dgn** [comment]
please ignore the release job; that's part of my `feature builds` work. sorry for the trouble, I made it opt-in now

**Comment by luksa** [comment]
@jwendell can you review this again? thanks

**Review by jwendell — APPROVED** [review]

**Pull request merged**
