### PR TITLE
MAISTRA-1160 Make sure custom Jaeger instances are accessible through…

### PR DESCRIPTION
**Pull request by dgn**
… Routes

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Review by luksa — APPROVED** [review]

**Review by knrc — CHANGES_REQUESTED** [review]
Do we not have to remove the istio-jaeger-ingress NetworkPolicy?

**Comment by dgn** [comment]
> Do we not have to remove the istio-jaeger-ingress NetworkPolicy?

I didn't remove it which leads to following behaviour:
- if we deploy Jaeger ourselves, we only create a single NP with the correct assumptions about labels (that is still istio-jaeger-ingress, which is only deployed when `tracing.enabled==true`)
- if the user specifies a custom Jaeger instance, we fall back to creating two NPs to match both all-in-one and production (the NPs in this PR)

I agree that the simpler solution would be to always create two NPs, but my assumption was that we should create the minimum necessary based on what we know. Let me know if I should change that.

**Comment by knrc** [comment]
I'm happy with the current approach if you are, thanks very much

**Review by knrc — APPROVED** [review]

**Pull request merged**
