### PR TITLE
MAISTRA-698 | Set Elasticsarch resources to 16gb and 1 CPU

### PR DESCRIPTION
**Pull request by pavolloffay**
Follow up on https://github.com/Maistra/istio-operator/pull/126/
Resolves: https://issues.jboss.org/browse/MAISTRA-698

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
@objectiser could you please have a look?

**Review by objectiser — COMMENTED** [review]
LGTM

**Review by rcernich — CHANGES_REQUESTED** [review]
This seems like something that should be configurable directly in the SMCP resource.  Hard coding to a large value like this might prevent installation in constrained environments.  We've experienced issues in the past where components fail to come up because of scheduling issues related to node resources.

**Comment by pavolloffay** [comment]
@rcernich I have made the resources configurable. I am not very familiar with help so please review carefully. 

Should the `.Values.jaeger.elasticsearch.resources` be defined somewhere?

**Comment by rcernich** [comment]
> Should the .Values.jaeger.elasticsearch.resources be defined somewhere?

Yep.  To test, you could add the following snippet to your SMCP resource:
```yaml
spec:
  istio:
    tracing:
      jaeger:
        elasticsearch:
          resources:
            requests:
              memory: "16Gi"
              cpu: "1"
            limits:
              memory: "16Gi"
```

**Comment by rcernich** [comment]
Just realized my snippet above uses the default configuration.  You should probably test with a different resources spec to ensure the template is expanding correctly.

**Comment by pavolloffay** [comment]
@rcernich I didn't manage to build the image and test it. Could somebody from maistra verify my patch? 

btw. the current installation instractions does not work as they reference tag  1.0.0 https://github.com/Maistra/istio-operator/blob/e62113a02379e02b3b7ba06129f8809a6ef5e42f/deploy/maistra-operator.yaml#L443, which does not exist https://hub.docker.com/r/maistra/istio-operator-ubi8/tags

**Comment by rcernich** [comment]
You'll need to modify the operator deployment after installation to point to your test image.

To build the image, you can use something like the following:
```
$ MAISTRA_VERSION=0.12.0 COMMUNITY=true IMAGE=<your-image-name> ./tmp/build/docker_build.sh
```

That will build the operator referencing 0.12.0 community release of maistra.

**Comment by pavolloffay** [comment]
@rcernich that instructions "as are" do not work either... It would be great to document how to build the project and image, add make targets which work out-of-the-box... 

I have used this to build the image
```
IMAGE=pavolloffay/istio-op:foo make dev/image
```

Changed the image in the deployment and deployed (all istio pods failed to deploy bc they reference image which is not on dockerhub `docker.io/maistra/citadel-ubi8:1.0.0`....)
```
oc apply -n istio-operator -f ./deploy/maistra-operator.yaml
```

Deployed modified minimal CR `oc create -f deploy/examples/maistra_v1_servicemeshcontrolplane_cr_minimal.yaml -n istio-system`

```yaml
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: minimal-install
spec:
  istio:
    global:
      proxy:
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
      istio-ingressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

    mixer:
      policy:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

      telemetry:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      # disable autoscaling for use in smaller environments
      autoscaleEnabled: false
      # increase random sampling rate for development/testing
      traceSampling: 100.0

    kiali:
      # to disable kiali
      enabled: false

      # create a secret for accessing kiali dashboard with the following credentials
      # dashboard:
      #   user: admin
      #   passphrase: admin

    # disable grafana
    grafana:
      enabled: false

    # to disable tracing (i.e. jaeger)
    tracing:
      enabled: true
      jaeger:
        # simple, all-in-one strategy
        template: production-elasticsearch
        elasticsearch:
          resources:
            requests:
              memory: "8Gi"
              cpu: "0.5"
            limits:
              memory: "8Gi"
        # production strategy, utilizing elasticsearch
        #template: production-elasticsearch
        # if required. only one instance may use agentStrategy=DaemonSet
        #agentStrategy: DaemonSet

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  # a list of namespaces that should be joined into the service mesh
  # for example, to add the bookinfo namespace
  #- bookinfo
```

Elasticsearch was created with modified resources:
```
 oc describe pod elasticsearch-cdm-istiosystemjaeger-1-68f86b4846-9ssm5 -n istio-system 

Name:           elasticsearch-cdm-istiosystemjaeger-1-68f86b4846-9ssm5
Namespace:      istio-system
Node:           localhost/192.168.90.113
Start Time:     Fri, 02 Aug 2019 10:20:23 +0200
Labels:         cluster-name=elasticsearch
                component=elasticsearch
                es-node-client=true
                es-node-data=true
                es-node-master=true
                node-name=elasticsearch-cdm-istiosystemjaeger-1
                pod-template-hash=2494260402
                tuned.openshift.io/elasticsearch=true
Annotations:    openshift.io/scc=restricted
Status:         Running
IP:             172.17.0.7
Controlled By:  ReplicaSet/elasticsearch-cdm-istiosystemjaeger-1-68f86b4846
Containers:
  elasticsearch:
    Container ID:   docker://ace4ac949ae215b3231c276ca10622a2691f79e6caa3bbd3b76f2257b5ba19f3
    Image:          quay.io/openshift/origin-logging-elasticsearch5
    Image ID:       docker-pullable://quay.io/openshift/origin-logging-elasticsearch5@sha256:9e370b765884dbd07ae6615698a32482511ca9e95f9af98a879ba541e588a396
    Ports:          9300/TCP, 9200/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 02 Aug 2019 10:20:24 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  8Gi
    Requests:
      cpu:      500m
      memory:   8Gi
    Readiness:  exec [/usr/share/elasticsearch/probe/readiness.sh] delay=10s timeout=30s period=5s #success=1 #failure=3
    Environment:
      DC_NAME:                  elasticsearch-cdm-istiosystemjaeger-1
      NAMESPACE:                istio-system (v1:metadata.namespace)
      KUBERNETES_TRUST_CERT:    true
      SERVICE_DNS:              elasticsearch-cluster
      CLUSTER_NAME:             elasticsearch
      INSTANCE_RAM:             8Gi
      HEAP_DUMP_LOCATION:       /elasticsearch/persistent/heapdump.hprof
      RECOVER_AFTER_TIME:       5m
      READINESS_PROBE_TIMEOUT:  30
      POD_LABEL:                cluster=elasticsearch
      IS_MASTER:                true
      HAS_DATA:                 true
    Mounts:
      /elasticsearch/persistent from elasticsearch-storage (rw)
      /etc/openshift/elasticsearch/secret from certificates (rw)
      /usr/share/java/elasticsearch/config from elasticsearch-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-token-nsf64 (ro)
  proxy:
    Container ID:  docker://5d8c93b908fb62ae04e5fc77ef0b1c1c5c3a3cef10949895baf8c02a9e43e2dc
    Image:         quay.io/openshift/origin-oauth-proxy:v4.0.0
    Image ID:      docker-pullable://quay.io/openshift/origin-oauth-proxy@sha256:f73bfe880c1caaf4a0a03cb6ffdb58baab2170e12ebafab26ea8e6abba66b3f4
    Port:          60000/TCP
    Host Port:     0/TCP
    Args:
      --https-address=:60000
      --provider=openshift
      --upstream=https://127.0.0.1:9200
      --tls-cert=/etc/proxy/secrets/tls.crt
      --tls-key=/etc/proxy/secrets/tls.key
      --upstream-ca=/etc/proxy/elasticsearch/admin-ca
      --openshift-service-account=elasticsearch
      -openshift-sar={"resource": "namespaces", "verb": "get"}
      -openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}
      --pass-user-bearer-token
      --cookie-secret=OX05qAcDXjY5uBdL5KZDyA==
    State:          Running
      Started:      Fri, 02 Aug 2019 10:20:24 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/proxy/elasticsearch from certificates (rw)
      /etc/proxy/secrets from elasticsearch-metrics (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-token-nsf64 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  elasticsearch-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      elasticsearch
    Optional:  false
  elasticsearch-storage:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elasticsearch
    Optional:    false
  elasticsearch-metrics:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elasticsearch-metrics
    Optional:    false
  elasticsearch-token-nsf64:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elasticsearch-token-nsf64
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   Scheduled              13m                 default-scheduler   Successfully assigned elasticsearch-cdm-istiosystemjaeger-1-68f86b4846-9ssm5 to localhost
  Normal   SuccessfulMountVolume  13m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "elasticsearch-storage"
  Normal   SuccessfulMountVolume  13m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "elasticsearch-config"
  Normal   SuccessfulMountVolume  13m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "elasticsearch-metrics"
  Normal   SuccessfulMountVolume  13m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "certificates"
  Normal   SuccessfulMountVolume  13m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "elasticsearch-token-nsf64"
  Normal   Created                13m                 kubelet, localhost  Created container
  Normal   Pulled                 13m                 kubelet, localhost  Container image "quay.io/openshift/origin-logging-elasticsearch5" already present on machine
  Normal   Started                13m                 kubelet, localhost  Started container
  Normal   Pulled                 13m                 kubelet, localhost  Container image "quay.io/openshift/origin-oauth-proxy:v4.0.0" already present on machine
  Normal   Created                13m                 kubelet, localhost  Created container
  Normal   Started                13m                 kubelet, localhost  Started container
  Warning  Unhealthy              11m (x14 over 12m)  kubelet, localhost  Readiness probe failed: Elasticsearch node is not ready to accept HTTP requests yet [response code: 000]
  Warning  Unhealthy              3m (x100 over 11m)  kubelet, localhost  Readiness probe failed: Elasticsearch node is not ready to accept HTTP requests yet [response code: 503]
```

**Comment by pavolloffay** [comment]
@rcernich could you please re-review?

**Comment by rcernich** [comment]
> @rcernich that instructions "as are" do not work either... It would be great to document how to build the project and image, add make targets which work out-of-the-box...
>
> I have used this to build the image
> `IMAGE=pavolloffay/istio-op:foo make dev/image`

The updates to integrate `make` were reverted, which is probably why the command I detailed above wasn't working.  Specifying `MAISTRA_VERSION=0.12.0` is used to set the image version, and the `COMMUNITY` variables specifies whether this is community or product build.

**Review by rcernich — APPROVED** [review]

**Review by jwendell — APPROVED** [review]

**Pull request merged**
