### PR TITLE
MAISTRA-2062: updated maistra CSV to support 1.1.11

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Comment by knrc** [comment]
Note the istio-operator_gen-check seems to be failing because of unrelated docs changes

**Comment by knrc** [comment]
and interestingly enough there are no differences if I run this locally other than the createdAt lines

**Comment by rcernich** [comment]
Yeah, the doc gen is unstable.  I have a PR which fixes the problem.

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
