### PR TITLE
Remove ca_file option in Kiali operator CR

### PR DESCRIPTION
**Pull request by israel-hdez**
Same as #502 but for `maistra-1.1` branch.
For fixing: https://issues.redhat.com/browse/MAISTRA-1719

### CODE REVIEW

**Comment by israel-hdez** [comment]
cc @rcernich @dgn

**Comment by rcernich** [comment]
@israel-hdez, you'll need to create a separate PR for the 1.0 changes, which will apply to the maistra-1.0 branch.

**Review by brian-avery — APPROVED** [review]

**Comment by israel-hdez** [comment]
Should I create the PR for 1.0 branch, or is this going to be cherry-picked automatically?

**Comment by rcernich** [comment]
I don't think we can cherry-pick, as the file structure differs, e.g. there is no helm/v1.1 directory in maistra-1.0.

JFYI, the idea here was that we'd be maintaining the charts specific to each istio release in its corresponding maistra branch, e.g. istio 1.1 charts are maintained in maistra-1.0, istio 1.4 charts in maistra-1.1, and istio 1.6 charts in maistra-2.0.  The rationale was that if we maintained them in a single branch, we'd need to maintain multiple patching scripts, etc.  In hindsight, though, I don't know if what we're doing today is any better than just maintaining all of them in a single branch.

**Comment by israel-hdez** [comment]
Here is the PR for 1.0 branch: https://github.com/maistra/istio-operator/pull/529

**Review by rcernich — APPROVED** [review]

**Pull request merged**
