### PR TITLE
Add installer flag

### PR DESCRIPTION
**Pull request by philipgough**
@knrc Feel free to dismiss this if not relevant. I was looking for away to make changes to the installer image and test without having to have a generic prefix that was forcing me to build all images.

Maybe I overlooked something and there was already a way.

### CODE REVIEW

**Comment by knrc** [comment]
@PhilipGough We made a deliberate decision to tie the installer to the images but we could certainly look at something like this.  You shouldn't need to rebuild all the containers to test though.

**Comment by philipgough** [comment]
@knrc Do they need to be tagged and pushed? So if I override the prefix and run a custom installer image it seemed to deploy all the istio images with the same prefix, can this be avoided?

**Comment by knrc** [comment]
@PhilipGough Are you running istiooc to test?

**Comment by philipgough** [comment]
Nope, workflow was create the cluster with the Maistra release (`istiooc cluster up`), modify the operator image and inject the prefix.

**Comment by knrc** [comment]
@PhilipGough If you are using istiooc then you can do it locally without having to rebuild everything.  The default behaviour of oc is to specify a 'pull always' policy but this can be overridden so your local images take precedence.  I'll send you some details later today.

**Comment by philipgough** [comment]
@knrc Cheers that would be great. FYI this was an ec2 machine and I'm on os x if that changes things.

**Pull request closed without merging**
