### PR TITLE
MAISTRA-1021: Fix the replaces value to allow upgrade

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Comment by knrc** [comment]
@dmitri-d Could you please cast you eye over this and make sure I've not forgotten anything else?

**Review by rcernich — APPROVED** [review]

**Comment by rcernich** [comment]
Is this a list field?  If so, should we list 1.0.0 and 1.0.1?  Also, these changes need to be made to maistra (community) version as well.

**Comment by knrc** [comment]
> Is this a list field? If so, should we list 1.0.0 and 1.0.1? Also, these changes need to be made to maistra (community) version as well.

There is a separate issue in this sprint for the community (maistra) config.

**Review by dmitri-d — APPROVED** [review]
lgtm

**Comment by knrc** [comment]
Note from the operator docs it looks as if replaces should just be a single version, forming a DAG through which older versions are discovered.

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
