### PR TITLE
OSSM-1698: Don't install istio-cni on nodes with label `maistra.io/exclude-cni: 'true'`

### PR DESCRIPTION
**Pull request by jewertow**

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by jwendell** [comment]
We should submit this upstream (with `istio.io` namespace) and then cherry pick once it's approved there.

**Comment by luksa** [comment]
Does upstream need this? I think the CNI node affinity can already be configured via `IstioOperator.components.cni.k8s` or something like this.

**Comment by jewertow** [comment]
> We should submit this upstream (with istio.io namespace) and then cherry pick once it's approved there.

@jwendell we already did it one year ago :D

**Comment by jewertow** [comment]
> then cherry pick once it's approved there

We can't cherry-pick it, because we don't use upstream istio-cni chart.

**Pull request merged**
