### PR TITLE
OSSM-3611 Fix readOnly argument in cert-manager and ca-root-cert volumeMount

### PR DESCRIPTION
**Pull request by aidy**

### CODE REVIEW

**Comment by jewertow** [comment]
@aidy thank you for the PR and I'm sorry for late reply. Could you rebase this branch?

**Comment by aidy** [comment]
@jewertow Done

**Comment by luksa** [comment]
@aidy Thank you for this PR. What issue does it solve? (I'd like to file it in our Jira)

**Comment by aidy** [comment]
@luksa It corrects the read-only argument that was intended to be specified for the volume mount. As it stands, it's an invalid specification and is silently ignored.

**Review by dgn — APPROVED** [review]

**Review by jewertow — APPROVED** [review]

**Pull request merged**
