### PR TITLE
MAISTRA-1508 Upgrade operator-sdk to 0.18.0

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Comment by rcernich** [comment]
Out of curiosity, do you know if they've improved support for webhooks, or is that part of newer OLM?

**Comment by luksa** [comment]
@rcernich I haven't looked at the webhooks yet.

**Comment by luksa** [comment]
@dgn Any chance you can review this? Apart from the changes to `vendor/`, the changes to our code are trivial and there aren't many, so it should take you more than a minute to review.

**Review by dgn — APPROVED** [review]
lgtm. sorry for taking so long, this has been below my radar for some reason

**Comment by luksa** [comment]
@Mergifyio refresh

**Comment by luksa** [comment]
I'll merge this manually, since mergify doesn't want to do it.

**Pull request merged**
