### PR TITLE
MAISTRA-2225: Update for 2.0.3 and 1.1.13

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by rcernich** [comment]
@luksa, you have to update the unit tests for the new versions.

**Comment by rcernich** [comment]
In the future, we should consider pinning the charts to specific tags, so that we only encounter these gen issues when we update the referenced tags to the latest release.

**Comment by rcernich** [comment]
These need to be updated: https://github.com/maistra/istio-operator/blob/maistra-2.1/pkg/controller/servicemesh/controlplane/profiles_test.go#L19-L21

**Review by rcernich — APPROVED** [review]

**Comment by luksa** [comment]
Thanks @rcernich

**Review by knrc — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
