### PR TITLE
[maistra-3.0] Pull 2.4 commits in

### PR DESCRIPTION
**Pull request by dgn**
I need these for the 3.0 support work

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by jwendell** [comment]
if 3.0 is going to be a mirror of 2.4 for a significant amount of time we can setup a job that syncs the branches automatically

**Comment by dgn** [comment]
> if 3.0 is going to be a mirror of 2.4 for a significant amount of time we can setup a job that syncs the branches automatically

I don't think so, this is really just to get something up and running

**Comment by jwendell** [comment]
we can always use the cherrypick labels when merging stuff in 2.4. But we might forget about it...

**Comment by dgn** [comment]
> we can always use the cherrypick labels when merging stuff in 2.4. But we might forget about it...

Yeah, that might be an idea. I'll demo what I have on Tuesday, we can use that as a base for discussion. I'm not sure how long it'll be until we diverge too much for that to work, but I hope it's not going to be long :)

**Pull request merged**
