### PR TITLE
OSSM-4753 Bump Versions to 2.2.11

### PR DESCRIPTION
**Pull request by mayleighnmyers**
https://issues.redhat.com/browse/OSSM-4753

### CODE REVIEW

**Comment by luksa** [comment]
The `maistra/istio` repo doesn't seem to have any new changes in branch [maistra-2.2](https://github.com/maistra/istio/commits/maistra-2.2) compared to branch [releases/2.2.10](https://github.com/maistra/istio/commits/releases/2.2.10) (click on these links and compare the commits), so why are we releasing 2.2.11?

**Comment by luksa** [comment]
Ah, I forgot about the base image changes.

**Review by luksa — APPROVED** [review]
LGTM

**Comment by luksa** [comment]
@mayleighnmyers How come this wasn't merged yet?

**Comment by mayleighnmyers** [comment]
> @mayleighnmyers How come this wasn't merged yet?

This also doesn't allow me to add the label

**Pull request merged**
