### PR TITLE
OSSM-4711: Remove default gateway installations

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
LGTM

**Review by luksa — APPROVED** [review]

**Comment by luksa** [comment]
Looks like the integration tests fail because they deploy a different operator image than the one built from this PR.

**Comment by jwendell** [comment]
> Looks like the integration tests fail because they deploy a different operator image than the one built from this PR.

haha it's clear now you don't read slack :D

TL,DR: https://github.com/openshift/release/pull/42799

**Pull request merged**
