### PR TITLE
MAISTRA-2671 Ensure Galley can start on OCP 4.9+

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by dgn — APPROVED** [review]

**Review by dgn — COMMENTED** [review]
Wait.. why do we also exclude Pod, Endpoints and Service?

**Comment by dgn** [comment]
> Wait.. why do we also exclude Pod, Endpoints and Service?

Is it to circumvent the CRD presence check on startup? I see in the code that galley will watch builtin types anyway, so I guess that's why it's okay to add them to the list?

**Comment by luksa** [comment]
> Wait.. why do we also exclude Pod, Endpoints and Service?

If you don't specify `--excludeResourceKinds`, it defaults to `Service,Endpoints,Pod,Node,Namespace` (see [1] and [2])

[1] https://github.com/Maistra/istio/blob/22bc71bcc46c9b6b4b4b3d5017a1b78d5efab327/galley/pkg/config/util/kuberesource/resources.go#L66
[2] https://github.com/Maistra/istio/blob/8dc359773107a150114e28c27ae85ae188c163ae/galley/pkg/source/kube/builtin/types.go#L46-L242

**Comment by luksa** [comment]
@dgn @jwendell any thoughts on whether to fix this with this PR or with https://github.com/maistra/istio/pull/438? Why aren't we fixing everything by changing the charts in maistra/istio instead of making things unnecessary complex via patch-charts?

**Comment by jwendell** [comment]
heh, this is a broader discussion we should have for 2.2 I think. JFYI, I agree with you, I'm against patching charts in operator.

**Comment by dgn** [comment]
+1 I think in the future we should be making all changes directly in maistra/istio, it's just so much easier than writing sed scripts. For this issue, I don't mind either way

**Comment by luksa** [comment]
OK, then let's go with this PR for now. I'll close the other one. @dgn can you approve this one?

**Review by dgn — APPROVED** [review]

**Comment by luksa** [comment]
Oops, sorry.. @dgn already approved it. @jwendell ?

**Review by jwendell — APPROVED** [review]

**Pull request merged**
