### PR TITLE
OSSM-1488 Add option to manually manage an SMCP-owned resource

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by dgn — APPROVED** [review]
LGTM, just needs a fix for the merge conflict

**Comment by jwendell** [comment]
@luksa Hey Marko, this needs a rebase

**Comment by JStickler** [comment]
It looks like this might require some user documentation.  Could you create a ticket in the OSSMDOC project with some additional details?  Much appreciated.

**Review by jwendell — COMMENTED** [review]
@luksa Is it worth to add tests for this?

**Comment by jwendell** [comment]
@JStickler Out of curiosity: do we need to document a techPreview feature? If yes, how? As a proper documentation or as a KB article?

**Comment by JStickler** [comment]
@jwendell Ah, didn't realize this was going to be a tech preview feature.  I just want to make sure that our documentation on Operator managed labels stays up-to-date and this looked like a change that might require a doc update.  We could document this either as a KB article or as a technology preview (If we're pretty sure this is eventually going to become a GA feature).

**Comment by luksa** [comment]
Closing. We'll fix this with some sort of overlays in the SMCP.

**Pull request closed without merging**
