### PR TITLE
OSSM-3288: Add ExtensionProviders

### PR DESCRIPTION
**Pull request by mayleighnmyers**
https://issues.redhat.com/browse/OSSM-3288 

Signed-off-by: Mayleigh Myers <mamyers@redhat.com>

### CODE REVIEW

**Comment by jewertow** [comment]
@mayleighnmyers please cherry-pick my commits from this branch: https://github.com/maistra/istio-operator/compare/maistra-2.4...jewertow:istio-operator:extension-providers.

**Comment by llomgui** [comment]
Hello @mayleighnmyers @jewertow,

Is it possible to include others extensionProviders?
I would need envoyExtAuthzHttp. 😃 

I can add commits by myself if needed.

**Comment by jewertow** [comment]
Hey @llomgui! `envoyExtAuthzHttp` is on our board and we are going to implement it right after this PR.

**Review by luksa — APPROVED** [review]

**Pull request merged**
