### PR TITLE
[MAISTRA-527] Protect `tracing` endpoint with OAuth

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by rcernich** [comment]
This overlaps the work being done for MAISTRA-203.

**Comment by jwendell** [comment]
@rcernich yeah, I guessed that. This is what I asked you on MAISTRA-527.

So, should I close this one?

**Comment by rcernich** [comment]
Sure, go ahead and close it.

**Comment by jwendell** [comment]
ok, just make sure to include the changes in this PR on yours.

**Pull request closed without merging**
