### PR TITLE
MAISTRA-2493 No need to turn ingressControllerMode=off manually

### PR DESCRIPTION
**Pull request by shamsher31**
Based on https://github.com/maistra/istio/pull/390#issuecomment-874092691

### CODE REVIEW

**Comment by shamsher31** [comment]
This is going to build once https://github.com/maistra/istio-operator/pull/766 is merged.

**Review by luksa — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
Why? Can you explain it in the commit message? Can you create a Jira for it?

**Comment by shamsher31** [comment]
> Why? Can you explain it in the commit message? Can you create a Jira for it?

@jwendell  Added JIRA for this https://issues.redhat.com/browse/MAISTRA-2493

**Review by jwendell — APPROVED** [review]

**Pull request merged**
