### PR TITLE
Pull in Istio chart changes (MAISTRA-322 and MAISTRA-329)

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
https://github.com/Maistra/istio/pull/86 must be merged before this goes in.

**Comment by luksa** [comment]
OK, this is now good to go. I've changed the prefix to `sidecar.maistra.io`  and re-tested everything.

**Review by rcernich — APPROVED** [review]

**Comment by luksa** [comment]
@dgn can you approve this.. it'll also fix the gen-check errors in your PR (#366)

**Review by dgn — APPROVED** [review]

**Pull request merged**
