### PR TITLE
MAISTRA-2436: Update operator metadata for maistra 2.0.6

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by knrc** [comment]
There was one part missing from the 1.1 PR, I've just submitted https://github.com/maistra/istio-operator/pull/745 to address it

**Review by shamsher31 — APPROVED** [review]

**Comment by jwendell** [comment]
`"Error rendering helm charts: error: failed to parse profile maistra contents: Object 'apiVersion' is missing in 'resources/smcp-templates/v2.0/maistra apiVersion`

**Comment by knrc** [comment]
@jwendell yeah, looks like I prepended the contents of the file with the filename.  Not quite sure how that happened but it is fixed.

**Pull request merged**
