### PR TITLE
MAISTRA-967 - Update Kiali CDR with inClusterURL for Tracing

### PR DESCRIPTION
**Pull request by aljesusg**
Related with https://github.com/kiali/kiali/pull/1628

cc @jmazzitelli

### CODE REVIEW

**Comment by aljesusg** [comment]
Hey can we merge this one @jwendell @dmitri-d @knrc ?

**Review by dgn — APPROVED** [review]
please also cherry-pick to `maistra-1.1`

**Comment by knrc** [comment]
We need a MAISTRA jira for this PR

**Comment by aljesusg** [comment]
Done @knrc . Thanks !!!

**Comment by lucasponce** [comment]
This is the JIRA:
https://issues.jboss.org/browse/MAISTRA-967

We will need this PR in Maistra 1.0.1 when Kiali 1.0.6.

I think that it can be merged and I will have no negative effect with kiali 1.0.5.

Please, @aljesusg @jmazzitelli confirm here otherwise.

**Comment by aljesusg** [comment]
Yes @lucasponce , in fact @knrc set the jira to 1.0.1 sprint

**Comment by aljesusg** [comment]
can we remove the work-in-progress @knrc ? this is ready to merge

**Comment by knrc** [comment]
@aljesusg The question wasn't whether this was ready to merge but whether we are ready to merge it.  I added the tag to prevent merging until we are ready.

I'm back at work today so will start looking through these, give me a day or so.

**Comment by aljesusg** [comment]
Oh great @knrc I thought that I was missing something . Thanks !!!

**Review by rcernich — APPROVED** [review]

**Pull request merged**
