### PR TITLE
Remove old versions from resources/

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Isn't this removed automatically when a version is removed from versions.yaml file and we run make gen?

**Comment by luksa** [comment]
Not yet.

**Comment by luksa** [comment]
@jwendell I've now implemented automatic removal. Please review again.

**Review by jwendell — COMMENTED** [review]
Isn't it easier to just remove the entire parent directory and recreate them on make gen with current values from versions.yaml?

**Comment by luksa** [comment]
> Isn't it easier to just remove the entire parent directory and recreate them on make gen with current values from versions.yaml?

Not sure. I don't really like the fact that we download everything every time you run `make gen`.

**Review by jwendell — APPROVED** [review]

**Pull request merged**
