### PR TITLE
MAISTRA-1024: Update servicemesh-manifests with MAISTRA-929 resources…

### PR DESCRIPTION
**Pull request by yxun**
… change

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Review by knrc — CHANGES_REQUESTED** [review]
Could we remove the resource sections from this example?  If we keep them then we will face a similar issue at a future time.

**Comment by yxun** [comment]
@knrc Yes. I removed the two resource sections in the second commit.

**Comment by yxun** [comment]
oops, wait a min. I need to delete more line. It's broken template now.

**Comment by yxun** [comment]
@knrc @rcernich Done. Could you help review this PR ?

The reason why I delete both the .spec.istio.global and .spec.istio.global.proxy block is : our operator could not parse block with empty content. So after I delete the .spec.istio.global.proxy.resources section, I have to delete .spec.istio.global and .spec.istio.global.proxy empty sections as well.

**Review by knrc — APPROVED** [review]

**Review by rcernich — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
