### PR TITLE
OSSM-1535 Remove objectSelector from validation webhook

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
Can we have a test to verify the validation webhook is always triggered?

**Comment by luksa** [comment]
> Can we have a test to verify the validation webhook is always triggered?

No.

It's possible that this type of test is in the istio repo already. We need to move our chart changes into the istio repo and run the tests there (instead of adding new tests to istio-operator).

**Comment by jwendell** [comment]
Even if these tests are done in upstream, given we change the charts I think we should add them. If this is not possible in unit tests, we should do them in e2e tests. Let me comment on the ticket.

**Comment by luksa** [comment]
I meant maistra/istio, not upstream. Since we make changes to the charts, we should move those changes to maistra/istio and run the istio integration tests with our charts.

**Pull request merged**
