### PR TITLE
OSSM-5351 Only install istio-cni when it's enabled in values.istio_cni.enabled

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
I think you need to change the integration test to only check CNI in OCP. Maybe if it's not OCP check if CNI is *not* deployed.

**Comment by luksa** [comment]
These tests don't run on OCP (or k8s). They use a fake API server.

I'll probably add with-CNI & without-CNI tests later (in a different PR) when I figure out how best to implement these tests.

**Comment by jwendell** [comment]
What do you mean? The integration test runs in a OCP / Kind cluster. I think the kind test is going to fail because of this.

**Comment by luksa** [comment]
This "[integration test](https://github.com/maistra/istio-operator/blob/97feba0298f6d3934cba17e9a2c4e77431a6821e/controllers/istio_controller_test.go#L36-L242)" does not run on OCP or k8s.

**Comment by jwendell** [comment]
https://github.com/maistra/istio-operator/blob/041ad705a7b474ebb36cb6c5873c86fd473f9aa7/tests/integration/common-operator-integ-suite.sh#L186

**Comment by luksa** [comment]
Ah, *that* integration test. :)

**Review by jwendell — APPROVED** [review]

**Pull request merged**
