### PR TITLE
MAISTRA-2459 Don't treat NotFound as an error when deleting a resource

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by jwendell** [comment]
@luksa ok to merge?

**Comment by luksa** [comment]
I don't know. This targets 2.0 and I have no idea whether we are free to merge things or not. :)

**Comment by jwendell** [comment]
cc @knrc

**Comment by knrc** [comment]
@luksa @jwendell +1, it was to be resubmitted after the release was tagged and that was done.

**Comment by dgn** [comment]
@luksa should this also be done in 2.1? I think there are a few spots where we treat NotFound as error still there

**Pull request merged**
