### PR TITLE
OSSM-4464 - remove image build

### PR DESCRIPTION
**Pull request by mattmahoneyrh**
Removing operator image build... because building the image does not belong within the scope of the test suite, but instead should be a dependency action that is done prior to running the tests.

### CODE REVIEW

**Comment by jwendell** [comment]
why?

**Comment by mattmahoneyrh** [comment]
Why should building the operator image have been included in an integration smoke test to begin with?

**Comment by yxun** [comment]
Matt explained to me there is an existing operator build make target so he is trying to remove this duplicate operator build step.

**Review by yxun — APPROVED** [review]

**Comment by mattmahoneyrh** [comment]
I am going to close this PR, because after talking through with @yxun the integration of these tests into the PROW job, there are efficiency improvements that are needed with the way the operator should be deployed and validated running.

**Pull request closed without merging**
