### PR TITLE
MAISTRA-2668 Set sideEffects on webhooks

### PR DESCRIPTION
**Pull request by luksa**
Cherry-pick of #849

### CODE REVIEW

**Comment by luksa** [comment]
@dgn This is a blocker for 2.0.8.

**Review by dgn — APPROVED** [review]
thanks @luksa. I assume you were able to successfully deploy a 1.1 control plane with these changes? Because I haven't tested that

**Comment by luksa** [comment]
@dgn On OCP 4.8, but 4.9 also requires https://github.com/maistra/istio/pull/438 (which I'll probably move to the istio-operator repo).

**Review by jwendell — APPROVED** [review]

**Comment by dgn** [comment]
https://github.com/maistra/istio-operator/pull/857 needs to be merged first

**Pull request merged**
