### PR TITLE
OSSM-2274 Only prune resources that reference the SMCP for which pruning is being performed

### PR DESCRIPTION
**Pull request by luksa**
This ensures that resources aren't deleted when you start with two SMCPs in the same namespace and then delete the one with the ErrMultipleSMCPs status.

### CODE REVIEW

**Comment by dgn** [comment]
Hmm, those lint failures look legit

**Comment by luksa** [comment]
Yeah, the lint failures are legit, but this PR doesn't modify those lines. The fix is in a separate PR: https://github.com/maistra/istio-operator/pull/1074

**Review by jwendell — APPROVED** [review]

**Pull request merged**
