### PR TITLE
Added olm metadata

### PR DESCRIPTION
**Pull request by dmitri-d**
This PR is using changes in https://github.com/Maistra/istio-operator/pull/154. ```specDescriptors``` section of the csv (should document "most important" fields in our CRD) needs to be completed.

### CODE REVIEW

**Comment by dmitri-d** [comment]
@rcernich ping

**Comment by rcernich** [comment]
Hey @dmitri-d, I made a few changes to the operator role since you posted this.  Can you update this PR, or wait until #154 is merged, so we have parity?  From then on, we'll need to require folks to update all three files if they change anything related to the operator install.

**Comment by dmitri-d** [comment]
@rcernich: updated istio-operator permissions with your latest changes

**Comment by knrc** [comment]
Please use the mergify process, if there are outstanding reviewers then please chase

**Pull request merged**
