### PR TITLE
OSSM-4102 - Add Annotation For network-attachment-definitions

### PR DESCRIPTION
**Pull request by mattmahoneyrh**
Fix operator crash that was happening due to insufficient network-attachment-definitions permissions.

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Why do we need to read/write this? What's it being used for?

**Comment by dgn** [comment]
> Why do we need to read/write this? What's it being used for?

This is for the global NetworkAttachmentDefinition that is part of the charts. The operator cannot create it unless it has this permission

**Comment by dgn** [comment]
@mattmahoneyrh you should check your `git` setup, the commit author is `root`

**Comment by dgn** [comment]
You'll need to run `make gen` again- it now also regenerates the OLM metadata which will include this new permission. This is something that I introduced in another PR.

**Review by dgn — APPROVED** [review]

**Comment by mattmahoneyrh** [comment]
Suggested changes have been made.

**Pull request merged**
