### PR TITLE
Do not hardcode GOARCH

### PR DESCRIPTION
**Pull request by yselkowitz**
CC: @knrc

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Do we need a Jira issue for this?

**Comment by knrc** [comment]
@jwendell We will do but this is related to Z/P so is not for the 1.1.0 sprint

**Review by knrc — APPROVED** [review]

**Comment by knrc** [comment]
@Mergifyio update

**Comment by knrc** [comment]
@Mergifyio rebase

**Pull request merged**
