### PR TITLE
Add v1.20.1 and v1.19.5, remove 1.19.4

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Do we want to keep 1.20.0 as this stage? We're not committed yet to support customers, so, I think for now we could keep just the latest version for each stream...

I think you can also bump 1.19.5.

**Comment by luksa** [comment]
I'd like to keep 1.20.0 so I can experiment with both minor and patch version upgrades.

**Pull request merged**
