### PR TITLE
OSSM-4752 Bump Versions to 2.3.8

### PR DESCRIPTION
**Pull request by mayleighnmyers**
https://issues.redhat.com/browse/OSSM-4752

### CODE REVIEW

**Comment by luksa** [comment]
The `maistra/istio` repo doesn't seem to have any new changes in branch [maistra-2.3](https://github.com/maistra/istio/commits/maistra-2.3) compared to branch [releases/2.3.7](https://github.com/maistra/istio/commits/releases/2.3.7) (click on these links and compare the commits), so why are we releasing 2.3.8?

**Comment by luksa** [comment]
Although there are no changes in these branches, there are changes in the underlying base images.

**Review by luksa — APPROVED** [review]
LGTM

**Comment by luksa** [comment]
@mayleighnmyers How come this wasn't merged yet?

**Comment by mayleighnmyers** [comment]
> @mayleighnmyers How come this wasn't merged yet?

It's not allowing me to add a okay to merge label

**Pull request merged**
