### PR TITLE
MAISTRA-486 - Update 3scale configuration

### PR DESCRIPTION
**Pull request by philipgough**
To support client side load balancing to the adapter, the service is made headless and some
additional options have been added around gRPC, to disable the logging and to configure
the max time to keep gRPC connections alive.

### CODE REVIEW

**Comment by philipgough** [comment]
@knrc this is just prepping for the changes need to support https://github.com/3scale/3scale-istio-adapter/pull/104

**Review by brian-avery — APPROVED** [review]

**Review by unleashed — APPROVED** [review]

**Comment by rcernich** [comment]
is there a related issue for this?

**Comment by philipgough** [comment]
@rcernich  It's related to changes merged into 3scale adapter for TP12 - https://github.com/3scale/3scale-istio-adapter/pull/104

**Comment by knrc** [comment]
The issue is https://issues.jboss.org/browse/MAISTRA-486

**Pull request merged**
