### PR TITLE
MAISTRA-718 | Make Jaeger Elasticsearch spec fully configurable

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves: https://issues.jboss.org/browse/MAISTRA-718

This makes Jaeger's Elasticsearch spec fully configurable.

@objectiser could you please review? 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
I have tested this with various CRs. For instance:

```yaml
    tracing:
      enabled: true
      jaeger:
        # simple, all-in-one strategy
        template: production-elasticsearch
        elasticsearch:
          nodeCount: 3
          redundancyPolicy: FullRedundancy
          storage:
            storageClassName: testing
            size: 5Gi
          nodeSelector:
            beta.kubernetes.io/os: "linux"
        # production strategy, utilizing elasticsearch
        #template: production-elasticsearch
        # if required. only one instance may use agentStrategy=DaemonSet
        #agentStrategy: DaemonSet
```

**Review by objectiser — COMMENTED** [review]
LGTM - although I would prefer to actually just copy the whole `.Values.jaeger.elasticsearch` node into the template, rather than deal with the individual child nodes.

**Comment by pavolloffay** [comment]
> LGTM - although I would prefer to actually just copy the whole .Values.jaeger.elasticsearch node into the template, rather than deal with the individual child nodes.

**Comment by pavolloffay** [comment]
> LGTM - although I would prefer to actually just copy the whole .Values.jaeger.elasticsearch node into the template, rather than deal with the individual child nodes.

Then we can't pass the ES spec directly because we are overriding the defaults. For instance by default we use 3 nodes and specific resources. Once https://github.com/jaegertracing/jaeger-operator/issues/560 is resolved and assuming the defaults are the same we could pass the ES spec directly

**Comment by objectiser** [comment]
@pavolloffay Or the maistra CR could define the defaults?

**Comment by pavolloffay** [comment]
The CR defines what will be created. The defaults here defines what will be created if the value is missing in the CR. So if you just create an empty spec it will still create a 3 node ES cluster.

If you agree with this, I am fine to pass there directly the whole ES spec.

**Comment by objectiser** [comment]
@pavolloffay Fine to wait for feedback from the maistra team - but that may be better - so if `elasticsearch` node not present, then may need to set `nodeCount` but also the default resources.

**Comment by pavolloffay** [comment]
@rcernich @knrc could you please review?

**Review by rcernich — APPROVED** [review]
lgtm

**Comment by pavolloffay** [comment]
@rcernich can this be merged?

**Review by jwendell — APPROVED** [review]

**Pull request merged**
