### PR TITLE
add basic crd docs

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

I still need to organize the output and remove the generated JSON schema.  Should probably also edit the field comments to get better doc output.  And filter out basic types like TypeMeta and ObjectMeta.

### CODE REVIEW

**Review by dgn — APPROVED** [review]
good stuff

**Comment by dgn** [comment]
Maybe we can add something to maistra.github.io that imports these

**Comment by rcernich** [comment]
Yeah, I think @brian-avery was going to look into possibly doing something.

**Review by luksa — APPROVED** [review]

**Comment by brian-avery** [comment]
@mergifyio refresh

**Pull request merged**
