### PR TITLE
[MAISTRA-691] Simplify and organize the build system

### PR DESCRIPTION
**Pull request by jwendell**
- Moved stuff from tmp/build to build
- Output dir is now _output
- We now have an initial Makefile. Main targets:
  - build (default): builds the operator
  - patch-charts: Patch the charts (mainly used in RPM creation)
  - dev/download-charts: Download and patch the charts
  - dev/image: Build a container image
- Remove conditional around patching 1.0 charts, we don't need to worry about 1.0 anymore.

The workflow for developers will be mainly:

export IMAGE=quay.io/user/operator
make dev/image

### CODE REVIEW

**Comment by dgn** [comment]
Am using that for my branch now. Thank you! It's cleaner than the one I hacked together for testing ;)

**Comment by jwendell** [comment]
It's far from perfection, but it's a start point towards a better build system.
I really want to use that branch for my next task, so, can we get this approved/merged and improve it over time?

**Review by brian-avery — APPROVED** [review]

**Review by dgn — APPROVED** [review]
lgtm

**Pull request merged**
