### PR TITLE
MAISTRA-1435 Add v1.2 entry to istio-cni-config ConfigMap

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by rcernich — CHANGES_REQUESTED** [review]
Can you also update the network name map?

https://github.com/Maistra/istio-operator/blob/maistra-1.2/pkg/controller/common/cni/cni.go#L28

**Comment by luksa** [comment]
@rcernich done.

**Comment by dgn** [comment]
please ignore the release job; that's part of my `feature builds` work. sorry for the trouble, I made it opt-in now

**Review by rcernich — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Pull request merged**
