### PR TITLE
MAISTRA-2462 Cache NetworkAttachmentDefinition objects

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
gen-check will pass once #762 is merged.

**Review by rcernich — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
Is this actually caching anything? Shouldn't you use the NAD-provided client/informers in order to make use of the cache benefit?

**Comment by rcernich** [comment]
The client provided by controller-runtime has an internal cache of its own, but only when using typed objects (i.e. not unstructured).

**Review by jwendell — APPROVED** [review]
Thanks.

**Pull request merged**
