### PR TITLE
MAISTRA-467 Prevent reconciling namespace in mesh when it's already in another mesh

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by knrc** [comment]
This needs to be done as part of the validation of the SMMR

**Comment by knrc** [comment]
-1 to merge

**Review by rcernich — APPROVED** [review]

**Comment by rcernich** [comment]
@knrc, while this should be handled through validation, is it still a good idea to prevent the operator from trying to reconcile two meshes into the same namespace?  I think this hardens the operator.

**Comment by jwendell** [comment]
Note that the base branch of this PR is 0.11

**Comment by rcernich** [comment]
@jwendell, thanks for catching that!

**Comment by luksa** [comment]
@knrc I've resolved the conflicts.

**Comment by knrc** [comment]
@luksa Thanks, I'll merge it now

**Pull request merged**
