### PR TITLE
OSSM-1918 Add Helm linter

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by luksa** [comment]
Helm v3.4.2 is used in the CI jobs. The linter complains because [1] is spread across multiple lines.  But these lines come from maistra/istio (see [2]) and upstream, so we shouldn't change them to make the linter happy. Because the helm linter is happy in maistra/istio, this means we're using a different helm version here.

[1] https://github.com/Maistra/istio-operator/blob/cf81dada3f28bd76d5588cadc5ede4b45779e574/resources/helm/v2.3/default/templates/mutatingwebhook.yaml#L5-L8
[2] https://github.com/maistra/istio/blob/maistra-2.3/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L3-L7

**Comment by luksa** [comment]
In maistra/istio, the helm version is v3.8.2 (look for "Helm version" in https://prow.maistra.io/log?container=test&id=1575456907248799744&job=istio-lint-2.3)

**Comment by jwendell** [comment]
@luksa looks good to merge.

**Pull request merged**
