### PR TITLE
Fix broken release notes link used in CSV

### PR DESCRIPTION
**Pull request by shamsher31**

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by shamsher31** [comment]
Thnaks @jwendell , this really helped.

```
$ make clean gen restore-manifest-dates
```

**Comment by brian-avery** [comment]
Would it be useful to have something like htmlproofer in this and other repos to make sure links stay correct?

**Review by brian-avery — APPROVED** [review]

**Comment by shamsher31** [comment]
> Would it be useful to have something like htmlproofer in this and other repos to make sure links stay correct?

That will be good to add.

But those links are in CSV yaml so not sure if it will work.

**Review by jwendell — APPROVED** [review]

**Pull request merged**
