### PR TITLE
MAISTRA-1153: adds ability to read pods and services for ior

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Review by dgn — APPROVED** [review]

**Review by jwendell — CHANGES_REQUESTED** [review]
You need to run `make update-1.1-charts` and commit the changes as well

**Review by rcernich — APPROVED** [review]

**Comment by rcernich** [comment]
Whoops, what @jwendell said.  Change looks good, but charts need to be regenerated or it won't get applied on install.

**Comment by bartoszmajsak** [comment]
> Whoops, what @jwendell said. Change looks good, but charts need to be regenerated or it won't get applied on install.

Sure, will do. Can this be automated though? i.e. GitHub action / prow job reacting on certain file changes should do the job, right? This way we always going to have consistency.

**Comment by bartoszmajsak** [comment]
Something is not right with this target, getting following changes all over the place

```
-    maistra-version: 1.1.0
+    maistra-version: 1.0.5
```

**Comment by jwendell** [comment]
make sure to run that command while checked out at `ior_roles` branch

**Comment by bartoszmajsak** [comment]
> make sure to run that command while checked out at `ior_roles` branch

I did. It turned out that I had `MAISTRA_VERSION` env var exported for some earlier shell-fu I was fiddling with and that is used by this target as well.

**Review by jwendell — APPROVED** [review]

**Review by jwendell — APPROVED** [review]

**Review by rcernich — APPROVED** [review]

**Pull request merged**
