### PR TITLE
OSSM-1107 Add jwksResolverExtraRootCA feature

### PR DESCRIPTION
**Pull request by yxun**
- This PR is related to OSSM-1107 and Istio PR 17176 https://github.com/istio/istio/pull/17176
- Add a new SMCP spec field as
  .spec.security.certificateAuthority.jwksResolverExtraRootCA

Signed-off-by: Yuanlin Xu <yuanlin.xu@redhat.com>

### CODE REVIEW

**Review by dgn — APPROVED** [review]
off to a great start, @yxun :)

**Comment by yxun** [comment]
Is there any suggestion about a new integration test ? which component(s) need to be covered when setting that field ?

**Comment by jwendell** [comment]
Why did you merge it now? Did you test it?

**Comment by yxun** [comment]
I wak checking tide and it was pending for a label. I will avoid adding that ok-to-merge label next time.

**Pull request merged**
