### PR TITLE
MAISTRA-1369 Fix handling of fully qualified image names

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by rcernich** [comment]
I think we need to modify patch-charts.sh so these changes aren't lost in a future change.

**Comment by dgn** [comment]
> I think we need to modify patch-charts.sh so these changes aren't lost in a future change.

+1, either that or modify the `maistra-1.0` branch of maistra/istio to fix them, that's where these charts are pulled in from

**Comment by luksa** [comment]
Yes, that's exactly what this PR is :)

**Comment by luksa** [comment]
Oh, s**t. For some reason, I thought they were pulled in from here. I get confused with all these repos and copying from one to another. I'll submit a PR against Maistra/istio.

**Comment by luksa** [comment]
Ah, nevermind. Rob already patches the charts in `patch-container-image.sh`. Closing this.

**Pull request closed without merging**
