### PR TITLE
bump version to v2.1.6

### PR DESCRIPTION
**Pull request by rcernich**
OSSM-2431 update goutils to v1.1.1

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Do you need to change https://github.com/maistra/istio-operator/blob/maistra-2.1/pkg/controller/servicemesh/controlplane/profiles_test.go#L23 ?

**Comment by rcernich** [comment]
@jwendell, tests pass locally

**Comment by rcernich** [comment]
I'll update the test, then figure out why it's passing locally.

**Pull request merged**
