### PR TITLE
MAISTRA-1885 Include manifest generation in `gen` target

### PR DESCRIPTION
**Pull request by dgn**

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by dgn** [comment]
Looks like we're using yqv2 in istio-operator but everywhere else we're using yqv3...

**Review by jwendell — APPROVED** [review]

**Comment by rcernich** [comment]
I believe the 3scale versions differ between product and community, one with the `v` prefix and one without.

**Comment by dgn** [comment]
> I believe the 3scale versions differ between product and community, one with the `v` prefix and one without.

Oh, you're right. Product doesn't use the `v` prefix. Will push a fix

**Pull request merged**
