### PR TITLE
threescale: configuration for adapter release 2.0

### PR DESCRIPTION
**Pull request by unleashed**
This PR supersedes #491 (you can safely close that one, /cc @PhilipGough).

Note that I had to apply https://github.com/unleashed/istio-operator/pull/1 to be able to run `make update-2.0-charts` due to unavailable dependencies. Let me know if you want me to post that PR here as well.

### CODE REVIEW

**Comment by rcernich** [comment]
I've integrated these changes as part of my work to add 3scale support into the new SMCP v2 resource.  Could you please verify the current versions of these files:

https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/helm/overlays/maistra-threescale/templates/deployment.yaml
https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/helm/overlays/maistra-threescale/values.yaml

Also, do we need to be using a new version of the 3scale adapter?  I believe we're still referencing 1.0.0.

**Comment by unleashed** [comment]
@rcernich the files look good. And yes, a new version of the 3scale adapter needs to be referenced, `2.0.0`.

**Comment by unleashed** [comment]
@rcernich so at this point with the changes you added I think we can close this issue. AFAICT the remaining issues are:

- [ ] Update 3scale-istio-adapter container image tags to `2.0.0`
- [ ] Consider whether https://github.com/unleashed/istio-operator/pull/1 is of any utility to you.

**Comment by rcernich** [comment]
@unleashed, can you provide a PR that updates the relevant files required to use the new image?  I assume you'll need to update:
https://github.com/maistra/istio-operator/blob/maistra-2.0/deploy/servicemesh-operator.yaml#L6978
https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/smcp-templates/v2.0/servicemesh#L38
https://github.com/maistra/istio-operator/blob/maistra-2.0/deploy/maistra-operator.yaml#L6978
https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/smcp-templates/v2.0/maistra#L38
https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/helm/overlays/maistra-threescale/templates/threescale-adapter.yaml
https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/helm/overlays/maistra-threescale/templates/threescale-authorization-template.yaml

**Comment by unleashed** [comment]
@rcernich sure! Done in #566.

**Comment by rcernich** [comment]
this work has been finished in other prs.

**Pull request closed without merging**
