### PR TITLE
MAISTRA-2055 make doc generation stable across executions

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

I can't guarantee that this fixes the problem, but after several runs, I have not seen any changes to the generated docs.

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Does this need a jira?
Also, don't forget to cherry-pick to 2.1. A comment `/cherrypick maistra-2.1` must be enough.

**Comment by rcernich** [comment]
I don't know.  It's just the tools code and shouldn't affect anything outside the docs folder (i.e. it's specifically related to the generation of those .adoc files).  The problem it fixes is pretty random and causes different docs to be generated intermittently (maybe 20% of the time).  For example, my PR yesterday, docs gen produced different results three times, which prevented the gen check from passing.  That said, I'm happy to add a JIRA, if you think it's necessary.

**Comment by knrc** [comment]
It should have a jira, ideally all commits to the repos should be traceable back to a jira

**Review by dgn — APPROVED** [review]

**Pull request merged**
