### PR TITLE
OSSM-1975 Use actual Kubernetes version when rendering charts (#1012)

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by jwendell** [comment]
Do we need to update 2.0 and 2.1 branches of operator?

**Comment by luksa** [comment]
@jwendell WDYM? This is a cherry-pick of #1012 that I'm now applying to all previous branches (see also #1030 and #1031).

**Comment by jwendell** [comment]
I meant.. it's unlikely we will release a new 2.0.x operator, right? People should use only the latest (2.2.x ATM) version of the operator, right?

**Comment by luksa** [comment]
Ah, I see what you mean. Yes, I wasn't sure, so I submitted PRs for all previous versions.

**Pull request closed without merging**
