### PR TITLE
MAISTRA-1113 Support deploying CRDs from multiple Maistra versions

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
@rcernich, @dgn this PR needs some reviewer love. Who's gonna provide it? :D

**Review by dgn — APPROVED** [review]
Looks fine. Should we add a test? Might also help future-us to understand why this is in place.

**Comment by luksa** [comment]
@dgn Thanks for reminding me about the test. I've added several tests. PTAL

**Review by dgn — APPROVED** [review]

**Review by rcernich — APPROVED** [review]

**Comment by dgn** [comment]
Looks like some of the new tests are flaky...

**Pull request merged**
