### PR TITLE
threescale: Prep for 2.0 release

### PR DESCRIPTION
**Pull request by philipgough**

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by unleashed** [comment]
Hi @brian-avery, the failed logs instruct to run `make gen` and commit any generated files. I think this might no longer be the case and re-running the CI could render this PR fully ready to merge, but not sure. Is there anything else missing? If not, then maybe re-running the `istio-operator_gen-check` step might be it.

**Comment by dgn** [comment]
Hi @unleashed @PhilipGough, the file you're changing is generated from the corresponding file in `resources/helm/overlays`: https://github.com/maistra/istio-operator/blob/maistra-2.0/resources/helm/overlays/maistra-threescale/templates/deployment.yaml

You'll need to make changes to that file, then run `make gen` and commit both changes here

**Comment by rcernich** [comment]
You need to change the files in overlays, then run `make update-2.0-charts`.  Your changes to `deployment.yaml` will be overwritten with whatever is in overlays.

**Comment by unleashed** [comment]
Please take a look at #522 and close this PR if it's ok.

**Comment by rcernich** [comment]
equivalent work has been merged in another pr

**Pull request closed without merging**
